// <auto-generated />
namespace milad.shop.Persistence.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class CustomerAggrigateAdded : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CustomerAggrigateAdded));
        
        string IMigrationMetadata.Id
        {
            get { return "202203020748393_CustomerAggrigateAdded"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
